---

# -------------------------------------------------------------------------------------------------
# Job Name
# -------------------------------------------------------------------------------------------------
name: params for schedule master


# -------------------------------------------------------------------------------------------------
# Custom Variables
# -------------------------------------------------------------------------------------------------
env:
  VERSIONS: >
    [
      {
        "NAME":    "PHP",
        "VERSION": ["8.1", "8.2", "8.3", "8.4"],
        "FLAVOUR": ["default"],
        "ARCH":    ["linux/amd64"]
      }
    ]
  REFS: >
    {
        "DEFAULT_BRANCH": ${{ format('"{0}"', github.event.repository.default_branch) }},
        "BRANCHES": ${{ format('"{0}"', github.event.repository.default_branch) }},
        "NUM_LATEST_TAGS": 0
    }


# -------------------------------------------------------------------------------------------------
# When to run
# -------------------------------------------------------------------------------------------------
on:
  workflow_call:
    ###
    ### OUTPUTS
    ###
    outputs:
      versions:
        description: "JSON string for versions. Use via: fromJson(needs.params.versions)"
        value: ${{ jobs.params.outputs.versions }}
      refs:
        description: "JSON string for refs. Use via: fromJson(needs.params.refs)"
        value: ${{ jobs.params.outputs.refs }}

jobs:
  params:
    runs-on: ubuntu-latest

    outputs:
      versions: ${{ steps.set-versions.outputs.versions }}
      refs: ${{ steps.set-refs.outputs.refs }}

    steps:
      - name: "[Set-Output] jsonify VERSIONS"
        id: set-versions
        run: |
          VERSIONS="$( echo '${{ env.VERSIONS }}' | jq -M -c )"
          echo "versions=${VERSIONS}" >> $GITHUB_OUTPUT

      - name: "[Set-Output] jsonify REFS"
        id: set-refs
        run: |
          REFS="$( echo '${{ env.REFS }}' | jq -M -c )"
          echo "refs=${REFS}" >> $GITHUB_OUTPUT
